# -*- coding: utf-8 -*-
"""Python Day-2 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsueaoMh-GZaznJ8vqbr5o1six1cdCVL

# List
"""

list1= ["one",2,"three",4,"five"]
list1.append(6) #append() adds the obj passed to list
print (list1)
list2=["seven",8]
list1.extend(list2) #extend() is used to append other list to existing list
print(list1)
list1.reverse() #reverse the elements of list
print(list1)
list1.remove(8) #removes the obj we have passed
print(list1)
print(list1.index(6)) #return index value of passed obj
print(len(list1)) #Returns the number of items in the list

"""# Dictionary"""

dictn= {"name":"sai","age":22,"number":9876543210}
dictn1= {"gender":"male"}
print(len(dictn))# returns length of dictionary
print(dictn.items())# returns all items in dictionary
print(dictn.keys())# return all key in dictionary
print(dictn.values())# return all values in dictionary
dictn.update(dictn1)# adds one dictionary to another dictionary
print(dictn)

"""# Sets"""

set1={"BMW","FORD","MARUTISUZUJI","TATA","HUNDAI"}
set1.add("HONDA") #used to add object to existing set
print(set1)
set2= set1.copy() #used to make multiple copies of existing set
print(set2)
set3={"KIA","MG","HONDA","FORD"}
print(set1.difference(set3)) #prints uncommon objects in set
set1.pop() # removes an object randomly
print(set1)
set1.remove("TATA") # removes specified object from set
print(set1)

"""# Tuple"""

tup =(0,1,2,2,3,4,5,6)
print(len(tup))
print("2 is repeated times",tup.count(2)) #counts the passed obj in tuple
print("index of 5 is",tup.index(5)) #gives index of passed obj

"""# String"""

str = "pythoN world"
print(str.capitalize()) #Capitalize first letter
print(str.swapcase()) #Invert the case of all letters
print(str.upper()) #Change lower case to upper case
print(str.isdigit()) #Return true if string has only digits
print(str.isalpha()) #Return True if there are only alphabets, else false