# -*- coding: utf-8 -*-
"""Python day-5 assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJpkhrK8LslqNraxtnPnscpNuvkZaH2l

##Write a program to identify sub list [1,1,5] is there in the given list in the same order, if yes print
“it’s a Match” if no then print “it’s Gone” in function.
"""

slst =[1,1,5]
lst=[6,4,1,8,4,9,1,6,5,7,1]
temp=[]
te=[1,1,5]
a=0
for i in slst:
    for j in lst:
        if i==j:
            temp.append(i)
            d= lst.index(j)
            del lst[0:d+1]
            lst=lst
            break
if temp==te:
    print("it's a match")
else:
    print("it's gone")

"""##Make a Function for prime numbers and use Filter to filter out all the prime numbers from 1-2500"""

lst = list(range(2500))
def prime(number):
        if number>1:
            for i in range(2, number):
                if number % i == 0:
                    return False
                    break
            else:
                return True
 
lsty= filter(prime,lst)
print(list(lsty))

"""##Make a Lambda function for capitalizing the whole sentence passed using arguments.
And map all the sentences in the List, with the lambda functions
"""

lst =["hey guys","please subscribe to","letsupgrade youtube channel"]
 
capitallambaversion = lambda text : text.title()
capitallambaversion (str(lst))
 
#directly passing lambda function as argument
#lstmap = map(lambda text:text.title(),lst)
 
#indirect method
lstmap = map(capitallambaversion,lst)
print(list(lstmap))