# -*- coding: utf-8 -*-
"""Python day-4 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APpOIPV1uBMzICEWMHYqfos1Fi8ccy1y

#Print the first ArmStrong number in the range of 1042000 to 702648265 and exit the loop as soon
as you encounter the first armstrong number.
Use while loop
"""

for number in range(1042000,702648265):
    order=len(str(number))
    temp=number
    sum=0
    while temp>0:
        d=temp%10
        sum=sum+d**order
        temp=temp//10
    if number==sum:
        print(number, "is first Armstrong number between 1042000 and 702648265")
        break