# -*- coding: utf-8 -*-
"""Python day-8 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hg5WRFsOUQTQNnA8PEKgmgLgqzukbEEq

##Write a decorator function for your taking input for you any kind of function you want to build,
For example - You make a fibonacci series function,in which your input range is been defined by
the decorator program input.
"""

def getinput(fibonacci):
    def wrap():
        print("enter two to get Fibonacci series")
        a=int(input("enter first number = "))
        b=int(input("enter second number = "))
        fibonacci(a,b)
    return wrap

@getinput
def getfibonacci(a,b):
        for i in range(10):
            print(a)
            print(b)
            c=a+b
            d=b+c
            a=c
            b=d

getfibonacci()

"""##For this challenge you need to develop a Python program to open a file in read only mode and try
writing something to it and handle the subsequent errors using Exception Handling.
"""

try:
    file = open("/Letsupgrade.txt","r")
    file.write("Letsupgrade")
except:
    print("UnsupportedOperation: not Writable")