# -*- coding: utf-8 -*-
"""Python day-3 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xM9KXAQt0da_KbRcpIwJGdJUfTuG872L

You all are Pilots, you want to land a plane safely, so altitude required for landing a plane is
1000ft, if it is less than 1000 tell pilot to land the plane, or it is more than 1000 that but less than 5000ft ask
the pilot to “come down to 1000ft”, else if it more than 5000ft ask the pilot to “go around and try
later”
"""

altitude=1000
caltitude = input("please enter your current altitude : ")
caltitude=int(caltitude)
if caltitude<=1000:
    print("It is safe to land")
elif caltitude>1000 and caltitude<5000:
    print("your altitude is", caltitude, "come down to 1000ft for landing")
else:
    print("your altitude is", caltitude, "go around and try later")

"""Using for loop please print all the prime numbers between 1- 200 using FOR LOOP AND RANGE
function.
"""

for number in range(1,200):
    if number>1:
        for i in range(2, number):
            if number % i == 0:
                break
        else:
            print(number)